coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

ignore:
  - "test/**"
  - "entrypoint.sh"
  - "*.md"
  - "*.yml"
  - "Dockerfile"
  - "LICENSE"
